# #clean automatically converted pdfs (like *-converted-to.pdf) and graphics (*.eps and *.pdf) generated by inkscape latex output feature
# #subdir is hardcoded here
# $clean_ext = '*.pdf *.pdf_tex';
# #clean files generated by custom dependencies
# $cleanup_includes_cusdep_generated = 1;
# #clean files generated by latex
# $cleanup_includes_generated = 1;
# #use recorder feature to list input files
# $recorder = 1;

# use File::Basename;

# #$pdflatex = 'pdflatex --shell-escape -interaction=batchmode -synctex=1 %O %S';
# #$latex = 'latex --shell-escape -interaction=batchmode -synctex=1 %O %S';

# #add synctex extensions so they are cleaned
# #push @generated_exts, 'synctex', 'synctex.gz';

# add_cus_dep('svg', 'pdf_tex', 0, 'svg2pdf_tex');
# sub svg2pdf_tex {
        # return system("inkscape --export-area-drawing --export-latex --export-pdf=\"$_[0].pdf\" \"$_[0].svg\"");
# }
